// Auth Types
export const EMAIL_CHANGED = 'email_changed'
export const PASSWORD_CHANGED = 'password_changed'
export const LOADING_CHANGED = 'loading_changed'
export const LOGIN_USER_SUCCESS = 'login_user_success'
export const LOGIN_USER_FAIL = 'login_user_fail'
export const LOGIN_USER = 'login_user'
export const LOGOUT_USER = 'logout_user'
export const LOGOUT_USER_SUCCESS = 'logout_user_success'
export const LOGOUT_USER_ERROR = 'logout_user_error'
export const SIGNUP_USER = 'signup_user'
export const SIGNUP_USER_SUCCESS = 'signup_user_success'
export const SIGNUP_USER_FAIL = 'signup_user_fail'
export const EMPLOYEE_UPDATE = 'employee_update'
export const EMPLOYEE_CREATE = 'employee_create'
export const EMPLOYEE_FETCH_SUCCESS = 'employee_fetch_success'
export const EMPLOYEE_SAVE_SUCCESS = 'employee_save_success'

// Wallet Types
export const WALLET_UPDATE = 'wallet_update'
export const WALLET_SET_RETAILER = 'wallet_set_retailer'
export const WALLET_SET_VALUE = 'wallet_set_value'
export const WALLET_ADD = 'wallet_add'
export const WALLET_REMOVE = 'wallet_remove'
export const WALLET_REMOVE_FAIL = 'wallet_remove_fail'
export const WALLET_FETCH = 'wallet_fetch'
export const WALLET_FETCH_SUCCESS = 'wallet_fetch_success'
export const WALLET_FETCH_FAIL = 'wallet_fetch_fail'
export const WALLET_SAVE_SUCCESS = 'wallet_save_success'
export const WALLET_GET_RETAILERS = 'wallet_get_retailers'
export const WALLET_GET_RETAILERS_SUCCESS = 'wallet_get_retailers_success'
export const WALLET_GET_RETAILERS_FAIL = 'wallet_get_retailers_fail'
